In [1]:
pip install tensorflow numpy matplotlib scikit-learn pillow

  Using cached matplotlib-3.10.8-cp312-cp312-win_amd64.whl.metadata (52 kB)
  Using cached scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
  Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached fonttools-4.61.1-cp312-cp312-win_amd64.whl.metadata (116 kB)
  Using cached kiwisolver-1.4.9-cp312-cp312-win_amd64.whl.metadata (6.4 kB)
  Using cached scipy-1.17.0-cp312-cp312-win_amd64.whl.metadata (60 kB)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached matplotlib-3.10.8-cp312-cp312-win_amd64.whl (8.1 MB)
Using cached scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.61.1-cp312-cp312-win_amd64.whl (2.3 MB)
Using cached joblib-1.5.3-py3-none-any

In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.models import Model
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import numpy as np


In [3]:
IMG_SIZE = 224
BATCH_SIZE = 32
EPOCHS = 10


In [4]:
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=15,
    zoom_range=0.2,
    shear_range=0.1,
    horizontal_flip=True
)


In [5]:
test_datagen = ImageDataGenerator(rescale=1./255)


In [6]:
train_data = train_datagen.flow_from_directory(
    "dataset_new/train",
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary"
)

test_data = test_datagen.flow_from_directory(
    "dataset_new/test",
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary",
    shuffle=False
)


Found 2467 images belonging to 4 classes.
Found 433 images belonging to 4 classes.


In [7]:
base_model = EfficientNetB0(
    weights="imagenet",
    include_top=False,
    input_shape=(224,224,3)
)

base_model.trainable = False  # freeze pretrained layers


16705208/16705208 ━━━━━━━━━━━━━━━━━━━━ 5s 0us/step


In [8]:
x = GlobalAveragePooling2D()(base_model.output)
x = Dense(256, activation="relu")(x)
x = Dropout(0.4)(x)
output = Dense(1, activation="sigmoid")(x)

model = Model(inputs=base_model.input, outputs=output)


In [9]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)


In [10]:
history = model.fit(
    train_data,
    validation_data=test_data,
    epochs=EPOCHS
)


Epoch 1/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 63s 677ms/step - accuracy: 0.2493 - loss: -37.8296 - val_accuracy: 0.2517 - val_loss: -100.6065
Epoch 2/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 49s 629ms/step - accuracy: 0.2501 - loss: -221.1768 - val_accuracy: 0.2517 - val_loss: -367.3328
Epoch 3/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 48s 607ms/step - accuracy: 0.2501 - loss: -597.9841 - val_accuracy: 0.2517 - val_loss: -854.4589
Epoch 4/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 47s 600ms/step - accuracy: 0.2501 - loss: -1165.1449 - val_accuracy: 0.2517 - val_loss: -1524.2336
Epoch 5/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 47s 599ms/step - accuracy: 0.2501 - loss: -1941.8750 - val_accuracy: 0.2517 - val_loss: -2369.6572
Epoch 6/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 47s 601ms/step - accuracy: 0.2501 - loss: -2872.2625 - val_accuracy: 0.2517 - val_loss: -3381.4512
Epoch 7/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 47s 597ms/step - accuracy: 0.2501 - loss: -3977.3076 - val_accuracy: 0.2517 - val_loss: -4597.2314
Epoch 8/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 47s 597ms/

In [11]:
base_model.trainable = True


In [12]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-5),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)


In [13]:
history_fine = model.fit(
    train_data,
    validation_data=test_data,
    epochs=10
)


Epoch 1/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 188s 2s/step - accuracy: 0.2505 - loss: 9.7157 - val_accuracy: 0.2517 - val_loss: -5491.9912
Epoch 2/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 141s 2s/step - accuracy: 0.2521 - loss: -2.5102 - val_accuracy: 0.2517 - val_loss: -5930.4805
Epoch 3/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 140s 2s/step - accuracy: 0.2533 - loss: -1387.7382 - val_accuracy: 0.2517 - val_loss: -1567.6876
Epoch 4/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 140s 2s/step - accuracy: 0.2570 - loss: -11154.5967 - val_accuracy: 0.2379 - val_loss: -3440.0759
Epoch 5/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 148s 2s/step - accuracy: 0.3008 - loss: -15980.0781 - val_accuracy: 0.3187 - val_loss: -11849.0469
Epoch 6/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 145s 2s/step - accuracy: 0.3194 - loss: -18635.2676 - val_accuracy: 0.3256 - val_loss: -16149.2764
Epoch 7/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 148s 2s/step - accuracy: 0.3287 - loss: -20087.3320 - val_accuracy: 0.2771 - val_loss: -18086.5273
Epoch 8/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 147s 2s/step - ac

In [14]:
y_pred = model.predict(test_data)
y_pred = (y_pred > 0.5).astype(int)


14/14 ━━━━━━━━━━━━━━━━━━━━ 6s 369ms/step


In [15]:
print(classification_report(test_data.classes, y_pred))


              precision    recall  f1-score   support

           0       0.66      0.69      0.67       109
           1       0.22      0.64      0.33       109
           2       0.00      0.00      0.00       109
           3       0.00      0.00      0.00       106

    accuracy                           0.33       433
   macro avg       0.22      0.33      0.25       433
weighted avg       0.22      0.33      0.25       433



e:\CODING\WakeGuard\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\CODING\WakeGuard\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\CODING\WakeGuard\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [16]:
print(confusion_matrix(test_data.classes, y_pred))


[[ 75  34   0   0]
 [ 39  70   0   0]
 [  0 109   0   0]
 [  0 106   0   0]]


In [17]:
model.save("eye_state_model.h5")


In [18]:
threshold = 0.6
y_pred = (y_pred > threshold).astype(int)


In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.models import Model
import numpy as np


In [3]:
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=15,
    zoom_range=0.2,
    shear_range=0.1,
    horizontal_flip=True
)

test_datagen = ImageDataGenerator(
    rescale=1./255
)


In [4]:
train_data = train_datagen.flow_from_directory(
    "dataset_new/train",
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical"
)

test_data = test_datagen.flow_from_directory(
    "dataset_new/test",
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical",
    shuffle=False
)


Found 2467 images belonging to 4 classes.
Found 433 images belonging to 4 classes.


In [5]:
print(train_data.class_indices)


{'Closed': 0, 'Open': 1, 'no_yawn': 2, 'yawn': 3}


In [6]:
train_data = train_datagen.flow_from_directory(
    "dataset_new/train",
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical"   # 🔥 IMPORTANT
)

test_data = test_datagen.flow_from_directory(
    "dataset_new/test",
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical",
    shuffle=False
)


Found 2467 images belonging to 4 classes.
Found 433 images belonging to 4 classes.


In [7]:
print(train_data.class_indices)


{'Closed': 0, 'Open': 1, 'no_yawn': 2, 'yawn': 3}


In [8]:
Dense(4, activation="softmax")


<Dense name=dense, built=False>

In [9]:
loss="categorical_crossentropy"


In [10]:
base_model = EfficientNetB0(
    weights="imagenet",
    include_top=False,
    input_shape=(224,224,3)
)

base_model.trainable = False

x = GlobalAveragePooling2D()(base_model.output)
x = Dense(256, activation="relu")(x)
x = Dropout(0.4)(x)
output = Dense(4, activation="softmax")(x)

model = Model(inputs=base_model.input, outputs=output)

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)


In [11]:
model.fit(
    train_data,
    validation_data=test_data,
    epochs=10
)


Epoch 1/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 47s 512ms/step - accuracy: 0.2489 - loss: 1.4292 - val_accuracy: 0.2448 - val_loss: 1.3903
Epoch 2/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 39s 495ms/step - accuracy: 0.2404 - loss: 1.3898 - val_accuracy: 0.2448 - val_loss: 1.3863
Epoch 3/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 38s 480ms/step - accuracy: 0.2533 - loss: 1.3866 - val_accuracy: 0.2517 - val_loss: 1.3862
Epoch 4/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 37s 478ms/step - accuracy: 0.2477 - loss: 1.3868 - val_accuracy: 0.2517 - val_loss: 1.3862
Epoch 5/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 37s 478ms/step - accuracy: 0.2489 - loss: 1.3864 - val_accuracy: 0.2448 - val_loss: 1.3861
Epoch 6/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 38s 485ms/step - accuracy: 0.2586 - loss: 1.3880 - val_accuracy: 0.2517 - val_loss: 1.3859
Epoch 7/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 37s 477ms/step - accuracy: 0.2392 - loss: 1.3872 - val_accuracy: 0.2517 - val_loss: 1.3859
Epoch 8/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 37s 478ms/step - accuracy: 0.2550 - loss: 1.3863 - val_accu

In [12]:
base_model.trainable = True

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-5),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.fit(
    train_data,
    validation_data=test_data,
    epochs=10
)


Epoch 1/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 170s 2s/step - accuracy: 0.3944 - loss: 1.4347 - val_accuracy: 0.2517 - val_loss: 1.3890
Epoch 2/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 146s 2s/step - accuracy: 0.6372 - loss: 0.8913 - val_accuracy: 0.2517 - val_loss: 1.3907
Epoch 3/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 152s 2s/step - accuracy: 0.7353 - loss: 0.6596 - val_accuracy: 0.2333 - val_loss: 1.4488
Epoch 4/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 139s 2s/step - accuracy: 0.7965 - loss: 0.5321 - val_accuracy: 0.2448 - val_loss: 1.4631
Epoch 5/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 293s 4s/step - accuracy: 0.8119 - loss: 0.4521 - val_accuracy: 0.6559 - val_loss: 1.0746
Epoch 6/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 157s 2s/step - accuracy: 0.8464 - loss: 0.3838 - val_accuracy: 0.7968 - val_loss: 0.7389
Epoch 7/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 165s 2s/step - accuracy: 0.8719 - loss: 0.3306 - val_accuracy: 0.8707 - val_loss: 0.4787
Epoch 8/10
78/78 ━━━━━━━━━━━━━━━━━━━━ 172s 2s/step - accuracy: 0.8893 - loss: 0.2892 - val_accuracy: 0.8845 - v

In [14]:
model.save("Improved_Model.h5")


In [15]:
import json

class_labels = train_data.class_indices
print(class_labels)

with open("class_labels.json", "w") as f:
    json.dump(class_labels, f)


{'Closed': 0, 'Open': 1, 'no_yawn': 2, 'yawn': 3}
